### PR TITLE
Add bytes method to Response struct

### PR DESCRIPTION
**Pull request by laurocaetano**
This patch has a simple change to wrap the `reqwest::Response::bytes()` into the client `Response` struct. Additionally I've taken the liberty to do some cosmetic changes in the overall struct - I hope that's fine too.

Thanks @dodomorandi for opening up the issue.

Closes https://github.com/elastic/elasticsearch-rs/issues/160

### CODE REVIEW

**Review by dodomorandi — APPROVED** [review]

**Comment by russcam** [comment]
Hi @laurocaetano, please can you [sign the CLA](https://www.elastic.co/contributor-agreement) so that we can pull this in. Also, would you mind adding an integration test to https://github.com/elastic/elasticsearch-rs/blob/master/elasticsearch/tests/client.rs for a bytes response? The tests can be run with

```
cargo make  test-elasticsearch
```

which will spin up an elasticsearch docker instance to run against.

**Comment by laurocaetano** [comment]
Thanks so much @russcam! I'm going to work on that tomorrow morning :)

It feels good to do open-source again :heart:

**Comment by laurocaetano** [comment]
I've updated the PR adding the integration tests, thanks for the review!

----

A couple of notes on the integration tests:

The task `test-elasticsearch` [is private](https://github.com/elastic/elasticsearch-rs/blob/07b5add01aa63a01f035f38dc33d715f9a5fea93/Makefile.toml#L56), so I only ran the tests with `cargo make test`.

The integration tests only run when I set `TEST_SUITE=platinum`: This is due to [this condition](https://github.com/elastic/elasticsearch-rs/blob/07b5add01aa63a01f035f38dc33d715f9a5fea93/Makefile.toml#L57). I am not sure if that is intended though. The following change would behave as I would expect:

```diff
-condition = { env_set = [ "ELASTICSEARCH_URL" ], env = { "TEST_SUITE" = "platinum" } }
+condition = { env_set = [ "ELASTICSEARCH_URL", "TEST_SUITE" ] }
```
I also get failures when running the cert tests:

```
    certificate_certificate_validation
    default_certificate_validation
    fail_certificate_certificate_validation
    full_certificate_validation
``` 

But I did not have enough time to debug those failures as well. It is probably due to some lack of configuration when running the tests on my machine.

Please let me know what you think about these issues. Probably I am missing something on my configs.

**Review by russcam — APPROVED** [review]
> The task `test-elasticsearch` is private, so I only ran the tests with `cargo make test`.

My fault, the correct task is `cargo make test` 👍 

> The integration tests only run when I set TEST_SUITE=platinum: This is due to this condition. I am not sure if that is intended though.

That is intended because the tests include tests for TLS, which is only set up in the Elasticsearch docker when the TEST_SUITE is platinum. It looks like a change in https://github.com/elastic/elasticsearch-rs/commit/ac43b524b8aad8f8794ea3ea15c019cc82ed1436#diff-9375fd04332c86472d7be397ef09428cb86babd8826880a5835bd1d1c1bdbc08R8 changed the default test suite from platinum to free, so it needs to be run with

```
cargo make test --env TEST_SUITE=platinum
```

@swallez should the default test suite be changed to platinum, so just `cargo make test` will run the tests?

> I also get failures when running the cert tests:
> 
>     certificate_certificate_validation
>     default_certificate_validation
>     fail_certificate_certificate_validation
>     full_certificate_validation

Do you see this when running with TEST_SUITE platinum? I _suspect_ the issue is likely the assertions in the tests; the assertions try to accommodate differences across Windows, macOS and Linux. They pass for me locally on Windows and Ubuntu 18.04 through WSL2. I think these can be addressed separately to this PR, if you'd like to open a separate issue with details about your setup?

**Comment by laurocaetano** [comment]
> Do you see this when running with TEST_SUITE platinum? I suspect the issue is likely the assertions in the tests; the assertions try to accommodate differences across Windows, macOS and Linux. They pass for me locally on Windows and Ubuntu 18.04 through WSL2. I think these can be addressed separately to this PR, if you'd like to open a separate issue with details about your setup?

I tried running locally (Ubuntu 20.04) and the cert tests fail. Some of them fail with:

```
---- full_certificate_ca_chain_validation stdout ----
Error: Error { kind: Http(reqwest::Error { kind: Request, url: Url { scheme: "https", host: Some(Domain("localhost")), port: Some(9200), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }) }
```

I've created the issue: https://github.com/elastic/elasticsearch-rs/issues/167. I will invest a bit more time into it the next days, and understand the real issue in these failures on my machine.

**Comment by russcam** [comment]
Thanks @laurocaetano. 

I re-ran the tests now on Ubuntu 18.04 with WSL 2, and am seeing test failures. The TLS related dependencies of reqwest were updated between 0.10 and 0.11, so I suspect the tests need some adjustment, which we can follow up separately on #167.

**Comment by russcam** [comment]
Thank you for your contribution @laurocaetano! 👍

**Comment by laurocaetano** [comment]
Thanks for your support @russcam :+1:

**Pull request merged**
