### PR TITLE
BulkOperation builder implementations

### LINKED ISSUE #43: [ENHANCEMENT] Add BulkBodyBuilder/BulkRequestBuilder?
The current bulk API is a little raw/not very "Rusty". I understand that it matches the actual `bulk` REST API and that this library, in general, is meant to be a thin abstraction over the REST API.

That being said, is it within the scope of this library to add something like a [`BulkDocumentOperation`](https://docs.rs/elastic/0.21.0-pre.5/elastic/client/requests/bulk/struct.BulkDocumentOperation.html) from the `elastic` crate—used like [this](https://docs.rs/elastic/0.21.0-pre.5/elastic/client/requests/bulk/type.BulkRequestBuilder.html#method.send)? It would abstract over `update` vs. `index` vs. `delete` etc. and expose options for each like setting `source: true` for `update` to return the updated doc (which is available on [elastic-rs/elastic#master](https://github.com/elastic-rs/elastic/tree/master)).

### PR DESCRIPTION
**Pull request by russcam**
This commit introduces a collection of builders to help with the bulk API. The bulk
API accepts a collection of operations in newline delimited JSON format, where
each operation is represented as a header, followed by an optional source for the
operation. The builders provide functions to build each of the supported operations,
exposing the metadata options available for the operation. Operations can be converted
to a common Operation type which implements the Body trait.

Closes #43

### CODE REVIEW

**Comment by mwilliammyers** [comment]
This looks like the direction we should head. What about adding params like [`_source`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#docs-bulk-api-query-params) etc? 

Also, I think we should add an [`extend`](https://docs.rs/elastic/0.21.0-pre.5/elastic/client/requests/bulk/type.BulkRequestBuilder.html#method.extend) method that is generic over `IntoIterator` or `Iterator`. It was very handy to have.

**Comment by russcam** [comment]
> What about adding params like `_source` etc?

The query string params are covered on `Bulk`, the builder for the API call. for example

https://github.com/elastic/elasticsearch-rs/blob/9e7468a5447402bd74c364453ba3dd1cf5ffe3b1/elasticsearch/src/generated/root.rs#L115-L119

> I think we should add an `extend` method that is generic over IntoIterator or Iterator. It was very handy to have.

Looks like this would logically go onto `BulkOperations`, and change the signature of `body()` on `Bulk` to accept `BulkOperations` as opposed to `Vec<T> where T: Serialize` (and change the generic type parameter on the return type from `NdBody<T>`...

**Comment by russcam** [comment]
In https://github.com/elastic/elasticsearch-rs/pull/56/commits/48f37ca0d10e85046ebcfdbeb439e0e8fa0a6818, I've changed the `&'a str` fields on bulk operations to use `String`, with functions accepting `Into<String`. The usage of `&'a str` makes it awkward to work with when constructing operations inside a loop, for example

https://github.com/elastic/elasticsearch-rs/blob/48f37ca0d10e85046ebcfdbeb439e0e8fa0a6818/elasticsearch/tests/common/client.rs#L83-L86

I did consider using `Cow<str>` for these, but thought `Into<String>` might be a little easier to work with. What are your thoughts, @mwilliammyers?

**Comment by mwilliammyers** [comment]
Yeah, I vote for `Into<String>`, it is the most flexible and let's the caller decide what type to use.

We can revisit and use `Cow<str>` or `&'a str`—or something else—iff performance/no-std compatibility becomes an issue (I *highly* doubt it ever will).

**Comment by russcam** [comment]
Added `BulkOperations` from the test to the package. 

I think this PR is good to merge in for now. There's a couple of things that I think should be looked at after, such as `Bulk` accepting `Vec<T> where T:Body` for its `body` fn, which means wrapping `BulkOperations` in a `Vec` to be able to pass it, but I think this is OK for the moment.

**Comment by mwilliammyers** [comment]
What about:
```rust
where I: IntoIterator<Item=T>, T: Body
```
or 
```rust
where T: IntoIterator, T::Item: Body
```
Not sure which I like better 🙃

**Pull request merged**
