### PR TITLE
updated to tokio 1.0

### LINKED ISSUE #152: [ENHANCEMENT] Migration to tokio 1.0
**Is your feature request related to a problem? Please describe.**
Since tokio 0.3 was released, it would be great to migrate, otherwise it's necessary to wrap each future in a compatibility layer.

**Describe the solution you'd like**
Migration to tokio 0.3. Any dependencies can be wrapped in a compatibility layer until they get updated too.

**Describe alternatives you've considered**
tokio-compat-02 crate.

**Additional context**
https://tokio.rs/blog/2020-10-tokio-0-3

EDIT: Should now update to tokio 1.0

### PR DESCRIPTION
**Pull request by krojew**
closes #152

### CODE REVIEW

**Comment by krojew** [comment]
signed

**Comment by fteychene** [comment]
I tested the modification and it seems good :+1: .
The edits are equivalent as when I tried to update to tokio 0.3 before reqwest and hyper migrated.
As I'm not in the client team I can't start the Jenkins job  :sweat_smile:

**Comment by jeroenvanmaanen** [comment]
I would be delighted to see this on [crates.io](https://crates.io/), because then I can update my project to Tokio 1.0 ([archetype-rust-axon](https://github.com/dendrite2go/archetype-rust-axon)).

**Comment by Jasperav** [comment]
@russcam could you please have a look at this PR?

**Review by russcam — APPROVED** [review]
LGTM, thanks @krojew 👍

**Comment by Jasperav** [comment]
@russcam  thanks! When will this be available on crates?

**Comment by russcam** [comment]
@Jasperav[ It's up now 😃 ](https://crates.io/crates/elasticsearch)

**Pull request merged**
