### PR TITLE
core: bump elasticsearch package dependencies

### PR DESCRIPTION
**Pull request by silverjam**
This change bumps a few older dependencies to the latest versions.  I've run `cargo make build` and `cargo make test` -- both seem to pass.

### CODE REVIEW

**Comment by silverjam** [comment]
@dodomorandi @swallez @pquentin Hello, any chance you could help me get this merged?  Thank you!

**Comment by dodomorandi** [comment]
> @dodomorandi @swallez @pquentin Hello, any chance you could help me get this merged? Thank you!

I am not in the position of doing anything, I am just a contributor. Said that, I can suggest you to improve your PR before asking for a merge:
- perform a rebase and remove the "merge from main";
- avoid reformatting parts of the `Cargo.toml` (you could do that in a separated commit, but it is out of scope anyway);
- put bumps of specific crates that require changes in the code in separated commit;
- provide some reasoning behind bumping certain dependencies (you are only updating some of them, is there a reason behind this?).

As I said, I am _just a contributor_, but it is easy to imagine that if you put less possible work on the shoulders of the maintainers it is more probable to have your PR merged.

And... don't ping for get the PR merged, it generally only makes the discussion... more spicy, let's put in this way :wink:. A PR of mine was fine and it took more than 3 years, probably it is not a good thing but if the maintainers do not have the time to handle the PRs, pinging them does not help. Please, don't take my words in the wrong way, it is just a suggestion from someone who already saw some useless flame in other projects for exactly these reasons. Peace! :relaxed:

**Comment by swallez** [comment]
Thanks for the ping @silverjam. We're working on reviving this project and bring it to the next step. The first step (you can see it in recent commits) is to have the 8.15 APIs, update dependencies (there are more updates needed than the ones on this PR) and make a release.

I also agree with @dodomorandi: avoid reformatting files in the PR, unless this is a PR dedicated to mechanical reformatting. Not a big deal in this specific case, but worth keeping in mind for larger changes.

**Comment by silverjam** [comment]
> Thanks for the ping @silverjam. We're working on reviving this project and bring it to the next step. The first step (you can see it in recent commits) is to have the 8.15 APIs, update dependencies (there are more updates needed than the ones on this PR) and make a release.

Great, good to hear.  Thanks for the update.

**Comment by silverjam** [comment]
Will close this PR since updates are planned through a different path.  Thanks @swallez and @dodomorandi.

**Comment by silverjam** [comment]
> And... don't ping for get the PR merged, it generally only makes the discussion... more spicy, let's put in this way 😉. A PR of mine was fine and it took more than 3 years, probably it is not a good thing but if the maintainers do not have the time to handle the PRs, pinging them does not help. Please, don't take my words in the wrong way, it is just a suggestion from someone who already saw some useless flame in other projects for exactly these reasons. Peace! ☺️

Just a few notes on my perspective here, I understand not being pushy, but asking once or twice (politely) for some guidance on how to move an improvement forward seems fine to me.

That is to say, pushing up a PR and then not flagging it seems way too hands off given you have no idea how maintainers are handing their information flows from GitHub, some people don't have any alerting system setup or (like me) they just don't read any automated emails at all.

So, I understand maintains have limited time, but flagging something as important to you (by asking how to get it merged) seems like a useful data point. If it's important to me, it's probably useful/important to someone else.  For us, these dependency bumps prevent us from building 2 versions of some pretty large dependencies.

Again, the key part for me is to provide useful information while respecting boundaries.

**Pull request closed without merging**
