### PR TITLE
Update to 8.3.3

### PR DESCRIPTION
**Pull request by russcam**
This PR updates the client to 8.3.3:

- regenerates the client using the 8.3.3 STACK_VERSION
- updates deprecation warning test to use an API call that emits a deprecation warning in 8.x

### CODE REVIEW

**Comment by Jasperav** [comment]
@russcam when can this PR be merged?

**Comment by russcam** [comment]
@Jasperav It needs to be reviewed and merged by someone from the Elastic organization.

**Review by Brian-Williams — APPROVED** [review]

**Comment by swallez** [comment]
Thanks for having taken care of this @russcam! Since 8.4 is already out, I will not publish 8.3.3 to crates.io, but will promptly release 8.4.1.

**Comment by swallez** [comment]
... and done! Version 8.4.0 has been released! https://crates.io/crates/elasticsearch

**Pull request merged**
